kind = "web"
previewPath = "/"
title = "Almic Solutions"
version = "1.0.0"
id = "artifacts/salmic-solutions"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25376

[services.development]
run = "pnpm --filter @workspace/salmic-solutions run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/salmic-solutions", "run", "build" ]
publicDir = "artifacts/salmic-solutions/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25376"
BASE_PATH = "/"
